/**
 * FAST Engine Orchestrator
 * Microservice to orchestrate FAST Engine channel instances
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ChannelGet200ResponseInner {
    /**
    * Channel Id
    */
    'id': string;
    /**
    * Name of the channel
    */
    'name': string;
    'type': ChannelGet200ResponseInnerTypeEnum;
    /**
    * URL to playlist, VOD to loop or webhook
    */
    'url': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ChannelGet200ResponseInnerTypeEnum",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChannelGet200ResponseInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ChannelGet200ResponseInnerTypeEnum {
    Loop = 'Loop',
    Playlist = 'Playlist',
    WebHook = 'WebHook'
}

