/**
 * FAST Engine Orchestrator
 * Microservice to orchestrate FAST Engine channel instances
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChannelPostRequestOpts } from '../models/ChannelPostRequestOpts';
import { HttpFile } from '../http/http';

export class ChannelPostRequest {
  /**
   * Name of the channel
   */
  'name': string;
  'type': ChannelPostRequestTypeEnum;
  /**
   * URL to playlist or VOD to loop
   */
  'url': string;
  'opts'?: ChannelPostRequestOpts;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
      format: ''
    },
    {
      name: 'type',
      baseName: 'type',
      type: 'ChannelPostRequestTypeEnum',
      format: ''
    },
    {
      name: 'url',
      baseName: 'url',
      type: 'string',
      format: ''
    },
    {
      name: 'opts',
      baseName: 'opts',
      type: 'ChannelPostRequestOpts',
      format: ''
    }
  ];

  static getAttributeTypeMap() {
    return ChannelPostRequest.attributeTypeMap;
  }

  public constructor() {}
}

export enum ChannelPostRequestTypeEnum {
  Loop = 'Loop',
  Playlist = 'Playlist',
  WebHook = 'WebHook'
}
