/**
 * FAST Engine Orchestrator
 * Microservice to orchestrate FAST Engine channel instances
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChannelPostRequestOptsPreroll } from '../models/ChannelPostRequestOptsPreroll';
import { HttpFile } from '../http/http';

export class ChannelPostRequestOpts {
    /**
    * Use demuxed audio (default is true)
    */
    'useDemuxedAudio'?: boolean;
    /**
    * Use VTT subtitles (default is true)
    */
    'useVttSubtitles'?: boolean;
    /**
    * URI to default slate
    */
    'defaultSlateUri'?: string;
    /**
    * Comma separated list of languages, e.g. (\"en,ja\"). First one is defined to be default
    */
    'langList'?: string;
    /**
    * Comma separated list of subtitle languages, e.g. (\"en,ja\"). First one is defined to be default
    */
    'langListSubs'?: string;
    /**
    * Channel preset. Available presets are: DD, HEVC, ATMOS
    */
    'preset'?: string;
    'preroll'?: ChannelPostRequestOptsPreroll;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "useDemuxedAudio",
            "baseName": "useDemuxedAudio",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "useVttSubtitles",
            "baseName": "useVttSubtitles",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "defaultSlateUri",
            "baseName": "defaultSlateUri",
            "type": "string",
            "format": ""
        },
        {
            "name": "langList",
            "baseName": "langList",
            "type": "string",
            "format": ""
        },
        {
            "name": "langListSubs",
            "baseName": "langListSubs",
            "type": "string",
            "format": ""
        },
        {
            "name": "preset",
            "baseName": "preset",
            "type": "string",
            "format": ""
        },
        {
            "name": "preroll",
            "baseName": "preroll",
            "type": "ChannelPostRequestOptsPreroll",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChannelPostRequestOpts.attributeTypeMap;
    }

    public constructor() {
    }
}

